import React from 'react';
import { useIncident } from '../../lib/IncidentContext';
import { FileText, Download, CheckCircle2, Clock, ShieldCheck, ShieldAlert, Play } from 'lucide-react';
import { clsx } from 'clsx';
import type { ObservableSystemEvent } from '@exhausttrace/shared';

export const ReportTab: React.FC = () => {
  const { bundle, startIncident } = useIncident();

  if (!bundle || (bundle.events.length === 0 && !bundle.causalAnalysis)) {
    return (
      <div className="flex-1 p-8 overflow-y-auto bg-background flex flex-col items-center justify-center">
        <div className="max-w-md w-full glass-panel p-8 text-center flex flex-col items-center">
          <div className="w-16 h-16 rounded-full bg-primary/10 border border-primary/20 flex items-center justify-center mb-4">
            <FileText className="w-8 h-8 text-primary" />
          </div>
          <h2 className="text-xl font-bold text-textMain mb-2 tracking-wide">NO COMPLETED INCIDENT REPORT</h2>
          <p className="text-sm text-textMuted mb-6 leading-relaxed">
            No incident session data has been generated yet. Start an incident simulation and run analysis to produce an end-to-end evidence & diagnosis report.
          </p>
          <button
            onClick={() => startIncident()}
            className="flex items-center gap-2 px-5 py-2.5 bg-primary hover:bg-primaryHover text-white rounded-lg font-medium text-sm transition-colors shadow-lg"
          >
            <Play className="w-4 h-4 fill-white" />
            START INCIDENT SIMULATION
          </button>
        </div>
      </div>
    );
  }

  const topCandidate = bundle.causalAnalysis?.topCandidate;
  const hypotheses = bundle.causalAnalysis?.hypotheses ?? [];
  const events = bundle.events ?? [];
  const tickCount = bundle.playback.tick ?? 0;
  const createdDate = bundle.createdAt ? new Date(bundle.createdAt).toLocaleString() : 'N/A';
  const confidencePercent = topCandidate ? Math.round(topCandidate.confidence * 100) : 0;

  // Split hypotheses into contributed vs dismissed
  const contributedEvidence = hypotheses.filter(h => h.confidence >= 0.2);
  const dismissedEvidence = hypotheses.filter(h => h.confidence < 0.2);

  const getEventService = (e: ObservableSystemEvent): string => {
    return (e as any).serviceId || (e as any).callerService || 'system';
  };

  const getEventStatus = (e: ObservableSystemEvent): string => {
    return (e as any).status || 'INFO';
  };

  const getEventDetails = (e: ObservableSystemEvent): string => {
    if (e.type === 'RESOURCE_PRESSURE_CHANGED') {
      return `Resource ${(e as any).resource}: status changed to ${(e as any).status}`;
    }
    if (e.type === 'TIMEOUT_SPIKE') {
      return `Timeout spike from ${(e as any).callerService} to ${(e as any).dependencyService}`;
    }
    if (e.type === 'RETRY_SURGE') {
      return `Retry surge from ${(e as any).callerService} to ${(e as any).dependencyService}`;
    }
    if (e.type === 'LATENCY_DEGRADED') {
      return `Latency degraded to ${(e as any).latencyMs}ms`;
    }
    if (e.type === 'QUEUE_GROWTH') {
      return `Queue depth grew to ${(e as any).queueDepth}`;
    }
    return e.type;
  };

  const handleExportMarkdown = () => {
    const mdLines = [
      `# ExhaustTrace Incident Diagnostic Report`,
      ``,
      `**Incident ID**: ${bundle.incidentId || 'N/A'}`,
      `**Scenario ID**: ${bundle.scenarioId || 'N/A'}`,
      `**Status**: ${bundle.status}`,
      `**Created At**: ${createdDate}`,
      `**Time to Diagnosis (Ticks)**: ${tickCount} ticks`,
      ``,
      `---`,
      ``,
      `## 1. Primary Root Cause Verdict`,
      topCandidate 
        ? `- **Target Service**: \`${topCandidate.serviceId}\`\n- **Exhausted Resource**: \`${topCandidate.resource}\`\n- **Confidence**: ${confidencePercent}%`
        : `- *No definitive root cause candidate established yet.*`,
      ``,
      `---`,
      ``,
      `## 2. Evidence Matrix`,
      ``,
      `### A. Contributed to Verdict`,
      contributedEvidence.length > 0
        ? contributedEvidence.map(h => `- **${h.serviceId} / ${h.resource}**: Confidence ${(h.confidence * 100).toFixed(1)}% (Score: ${h.score.toFixed(1)})`).join('\n')
        : `- *None*`,
      ``,
      `### B. Dismissed as Noise`,
      dismissedEvidence.length > 0
        ? dismissedEvidence.map(h => `- **${h.serviceId} / ${h.resource}**: Confidence ${(h.confidence * 100).toFixed(1)}% (Filtered)`).join('\n')
        : `- *None*`,
      ``,
      `---`,
      ``,
      `## 3. Incident Event Timeline (${events.length} Events)`,
      events.length > 0
        ? events.map(e => `- [Tick ${e.tick}] **${getEventService(e)}** - ${e.type} (${getEventStatus(e)}): ${getEventDetails(e)}`).join('\n')
        : `- *No timeline events recorded.*`,
      ``,
      `---`,
      `*Report generated by ExhaustTrace Causal Debugger on ${new Date().toISOString()}*`
    ];

    const content = mdLines.join('\n');
    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `exhausttrace-report-${bundle.incidentId || 'session'}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex-1 p-6 overflow-y-auto bg-background space-y-6">
      {/* Top Header Card */}
      <div className="glass-panel p-6 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-3 mb-2">
            <span className="px-2.5 py-1 rounded text-xs font-mono font-bold bg-primary/20 text-primary border border-primary/30">
              REPORT #{bundle.incidentId || 'DRAFT'}
            </span>
            <span className={clsx(
              "px-2.5 py-1 rounded text-xs font-mono font-bold uppercase",
              bundle.status === 'COMPLETED' ? "bg-healthy/10 text-healthy border border-healthy/20" : "bg-info/10 text-info border border-info/20"
            )}>
              {bundle.status}
            </span>
          </div>
          <h1 className="text-2xl font-bold text-textMain tracking-tight">Incident Diagnostic Summary</h1>
          <p className="text-xs text-textMuted font-mono mt-1">Scenario: {bundle.scenarioId} | Created: {createdDate}</p>
        </div>

        <button
          onClick={handleExportMarkdown}
          className="flex items-center gap-2 px-4 py-2.5 bg-primary hover:bg-primaryHover text-white rounded-lg font-medium text-sm transition-colors shadow-md shrink-0"
        >
          <Download className="w-4 h-4" />
          EXPORT MARKDOWN (.MD)
        </button>
      </div>

      {/* Summary Stat Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="glass-panel p-5">
          <div className="flex items-center justify-between text-textMuted mb-2">
            <span className="text-xs font-medium uppercase tracking-wider">Root Cause Verdict</span>
            <ShieldAlert className="w-4 h-4 text-critical" />
          </div>
          <div className="text-xl font-bold text-textMain font-mono">
            {topCandidate ? `${topCandidate.serviceId} (${topCandidate.resource})` : 'UNRESOLVED'}
          </div>
          <div className="text-xs text-textMuted mt-1">
            {topCandidate ? `Identified with ${confidencePercent}% statistical confidence` : 'Awaiting additional telemetry'}
          </div>
        </div>

        <div className="glass-panel p-5">
          <div className="flex items-center justify-between text-textMuted mb-2">
            <span className="text-xs font-medium uppercase tracking-wider">Confidence Level</span>
            <CheckCircle2 className="w-4 h-4 text-healthy" />
          </div>
          <div className="text-xl font-bold text-healthy font-mono">
            {confidencePercent}%
          </div>
          <div className="text-xs text-textMuted mt-1">
            {contributedEvidence.length} supporting evidence vectors
          </div>
        </div>

        <div className="glass-panel p-5">
          <div className="flex items-center justify-between text-textMuted mb-2">
            <span className="text-xs font-medium uppercase tracking-wider">Time to Diagnosis</span>
            <Clock className="w-4 h-4 text-info" />
          </div>
          <div className="text-xl font-bold text-textMain font-mono">
            {tickCount} ticks
          </div>
          <div className="text-xs text-textMuted mt-1">
            Discrete simulation ticks elapsed
          </div>
        </div>
      </div>

      {/* Evidence Matrix */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Contributed to Verdict */}
        <div className="glass-panel p-5">
          <div className="flex items-center gap-2 mb-4 pb-3 border-b border-border">
            <ShieldAlert className="w-4 h-4 text-healthy" />
            <h3 className="font-semibold text-textMain text-sm uppercase tracking-wider">Contributed to Verdict</h3>
            <span className="ml-auto text-xs px-2 py-0.5 rounded bg-healthy/10 text-healthy font-mono">
              {contributedEvidence.length} items
            </span>
          </div>

          {contributedEvidence.length === 0 ? (
            <p className="text-xs text-textMuted italic">No significant evidence contributed yet.</p>
          ) : (
            <div className="space-y-3">
              {contributedEvidence.map((h, i) => (
                <div key={i} className="p-3 bg-surface/50 border border-border rounded-lg flex items-center justify-between">
                  <div>
                    <div className="text-sm font-semibold text-textMain">{h.serviceId}</div>
                    <div className="text-xs text-textMuted font-mono">Resource: {h.resource} | Score: {h.score.toFixed(1)}</div>
                  </div>
                  <div className="text-sm font-mono font-bold text-healthy">
                    {(h.confidence * 100).toFixed(0)}%
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Dismissed as Noise */}
        <div className="glass-panel p-5">
          <div className="flex items-center gap-2 mb-4 pb-3 border-b border-border">
            <ShieldCheck className="w-4 h-4 text-textMuted" />
            <h3 className="font-semibold text-textMain text-sm uppercase tracking-wider">Dismissed as Noise</h3>
            <span className="ml-auto text-xs px-2 py-0.5 rounded bg-surfaceHover text-textMuted font-mono">
              {dismissedEvidence.length} items
            </span>
          </div>

          {dismissedEvidence.length === 0 ? (
            <p className="text-xs text-textMuted italic">No candidates dismissed as noise.</p>
          ) : (
            <div className="space-y-3">
              {dismissedEvidence.map((h, i) => (
                <div key={i} className="p-3 bg-surface/30 border border-border/50 rounded-lg flex items-center justify-between opacity-75">
                  <div>
                    <div className="text-sm font-medium text-textMuted">{h.serviceId}</div>
                    <div className="text-xs text-textMuted/70 font-mono">Resource: {h.resource}</div>
                  </div>
                  <div className="text-xs font-mono text-textMuted">
                    {(h.confidence * 100).toFixed(0)}% (Filtered)
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Event Timeline Table */}
      <div className="glass-panel p-5">
        <h3 className="font-semibold text-textMain text-sm uppercase tracking-wider mb-4 pb-3 border-b border-border">
          Full Event Timeline ({events.length} Events)
        </h3>

        {events.length === 0 ? (
          <p className="text-xs text-textMuted italic">No events logged during this session.</p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs font-mono">
              <thead>
                <tr className="border-b border-border text-textMuted">
                  <th className="pb-2 font-medium">Tick</th>
                  <th className="pb-2 font-medium">Service</th>
                  <th className="pb-2 font-medium">Type</th>
                  <th className="pb-2 font-medium">Severity</th>
                  <th className="pb-2 font-medium">Details</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border/40">
                {events.map((e, idx) => {
                  const svc = getEventService(e);
                  const st = getEventStatus(e);
                  const dt = getEventDetails(e);
                  return (
                    <tr key={idx} className="hover:bg-surfaceHover/50 transition-colors">
                      <td className="py-2.5 text-textMain font-bold">{e.tick}</td>
                      <td className="py-2.5 text-info">{svc}</td>
                      <td className="py-2.5 text-textMain">{e.type}</td>
                      <td className="py-2.5">
                        <span className={clsx(
                          "px-1.5 py-0.5 rounded text-[10px] uppercase font-bold",
                          st === 'CRITICAL' ? "bg-critical/20 text-critical" :
                          st === 'ELEVATED' || st === 'HIGH' ? "bg-elevated/20 text-elevated" : "bg-info/20 text-info"
                        )}>
                          {st}
                        </span>
                      </td>
                      <td className="py-2.5 text-textMuted truncate max-w-xs">
                        {dt}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
};
